In [3]:
import numpy as np
import pandas as  pd

In [4]:
df = pd.read_csv(r'D:\ML Projects\SMS Spam Classifier\spam.csv', encoding='latin-1')

In [5]:
df.sample(5)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
5380,ham,Its sunny in california. The weather's just cool,NaN,NaN,NaN
3960,ham,Your dad is back in ph?,NaN,NaN,NaN
3779,ham,Then ur physics get a-?,NaN,NaN,NaN
2632,ham,I WILL CAL YOU SIR. In meeting,NaN,NaN,NaN
3529,ham,Tyler (getting an 8th) has to leave not long a...,NaN,NaN,NaN

In [6]:
# Steps involved:
# 1. Data Cleaning
# 2. EDA
# 3. Text Processing
# 4. Model
# 5. Evaluation
# 6. Improvement
# 7. Website
# 8. Deployment

## Data Cleaning

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [8]:
df.describe()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
count,5572,5572,50,12,6
unique,2,5169,43,10,5
top,ham,"Sorry, I'll call later","bt not his girlfrnd... G o o d n i g h t . . .@""","MK17 92H. 450Ppw 16""","GNT:-)"""
freq,4825,30,3,2,2

In [9]:
# Drop last 3 columns
df = df.iloc[:, :-3]

In [10]:
df

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [11]:
# Renaming the  columns
df.rename(columns={'v1' : 'target', 'v2' : 'text'}, inplace=True)
df.sample(5)

     target                                               text
3818    ham  sorry brah, just finished the last of my exams...
569     ham                         WOT U WANNA DO THEN MISSY?
3799   spam  We tried to contact you re your reply to our o...
2595   spam  Sunshine Quiz Wkly Q! Win a top Sony DVD playe...
2833    ham                      U sick still can go shopping?

In [12]:
# Label encoding

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [13]:
df['target'] = encoder.fit_transform(df['target'])

In [14]:
df.head(10)

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...
5       1  FreeMsg Hey there darling it's been 3 week's n...
6       0  Even my brother is not like to speak with me. ...
7       0  As per your request 'Melle Melle (Oru Minnamin...
8       1  WINNER!! As a valued network customer you have...
9       1  Had your mobile 11 months or more? U R entitle...

In [15]:
# Checking for duplicates

df.duplicated().sum()

403

In [16]:
df = df.drop_duplicates(keep='first')

In [17]:
df

      target                                               text
0          0  Go until jurong point, crazy.. Available only ...
1          0                      Ok lar... Joking wif u oni...
2          1  Free entry in 2 a wkly comp to win FA Cup fina...
3          0  U dun say so early hor... U c already then say...
4          0  Nah I don't think he goes to usf, he lives aro...
...      ...                                                ...
5567       1  This is the 2nd time we have tried 2 contact u...
5568       0              Will Ì_ b going to esplanade fr home?
5569       0  Pity, * was in mood for that. So...any other s...
5570       0  The guy did some bitching but I acted like i'd...
5571       0                         Rofl. Its true to its name

[5169 rows x 2 columns]

In [18]:
df['target'].value_counts()

target
0    4516
1     653
Name: count, dtype: int64

In [19]:
import matplotlib.pyplot as plt

In [20]:
plt.pie(df['target'].value_counts(), labels=['ham', 'spam'], autopct='%0.2f')
plt.show()

C:\Users\Corei5_8GBRAM_512SSD\AppData\Local\Temp\ipykernel_12996\2309352643.py:2: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [21]:
import nltk

In [22]:
df['num_chars'] = df['text'].apply(len)

C:\Users\Corei5_8GBRAM_512SSD\AppData\Local\Temp\ipykernel_12996\1410551383.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_chars'] = df['text'].apply(len)

In [23]:
df.head()

   target                                               text  num_chars
0       0  Go until jurong point, crazy.. Available only ...        111
1       0                      Ok lar... Joking wif u oni...         29
2       1  Free entry in 2 a wkly comp to win FA Cup fina...        155
3       0  U dun say so early hor... U c already then say...         49
4       0  Nah I don't think he goes to usf, he lives aro...         61

In [24]:
df['text'].apply(lambda x: nltk.word_tokenize(x))

0       [Go, until, jurong, point, ,, crazy, .., Avail...
1                [Ok, lar, ..., Joking, wif, u, oni, ...]
2       [Free, entry, in, 2, a, wkly, comp, to, win, F...
3       [U, dun, say, so, early, hor, ..., U, c, alrea...
4       [Nah, I, do, n't, think, he, goes, to, usf, ,,...
                              ...
5567    [This, is, the, 2nd, time, we, have, tried, 2,...
5568     [Will, Ì_, b, going, to, esplanade, fr, home, ?]
5569    [Pity, ,, *, was, in, mood, for, that, ., So, ...
5570    [The, guy, did, some, bitching, but, I, acted,...
5571                  [Rofl, ., Its, true, to, its, name]
Name: text, Length: 5169, dtype: object

In [25]:
df['num_words'] = df['text'].apply(lambda x: len(nltk.word_tokenize(x)))

C:\Users\Corei5_8GBRAM_512SSD\AppData\Local\Temp\ipykernel_12996\2435226368.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_words'] = df['text'].apply(lambda x: len(nltk.word_tokenize(x)))

In [26]:
df.head()

,target,text,num_chars,num_words
0,0,"Go until jurong point, crazy.. Available only ...",111,24
1,0,Ok lar... Joking wif u oni...,29,8
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155,37
3,0,U dun say so early hor... U c already then say...,49,13
4,0,"Nah I don't think he goes to usf, he lives aro...",61,15

In [27]:
df['text'].apply(lambda x: nltk.sent_tokenize(x))

0       [Go until jurong point, crazy.., Available onl...
1                        [Ok lar..., Joking wif u oni...]
2       [Free entry in 2 a wkly comp to win FA Cup fin...
3       [U dun say so early hor... U c already then sa...
4       [Nah I don't think he goes to usf, he lives ar...
                              ...
5567    [This is the 2nd time we have tried 2 contact ...
5568              [Will Ì_ b going to esplanade fr home?]
5569    [Pity, * was in mood for that., So...any other...
5570    [The guy did some bitching but I acted like i'...
5571                        [Rofl., Its true to its name]
Name: text, Length: 5169, dtype: object

In [28]:
df['num_sentences'] = df['text'].apply(lambda x: len(nltk.sent_tokenize(x)))

C:\Users\Corei5_8GBRAM_512SSD\AppData\Local\Temp\ipykernel_12996\589552786.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_sentences'] = df['text'].apply(lambda x: len(nltk.sent_tokenize(x)))

In [29]:
df.head()

,target,text,num_chars,num_words,num_sentences
0,0,"Go until jurong point, crazy.. Available only ...",111,24,2
1,0,Ok lar... Joking wif u oni...,29,8,2
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155,37,2
3,0,U dun say so early hor... U c already then say...,49,13,1
4,0,"Nah I don't think he goes to usf, he lives aro...",61,15,1

In [30]:
df[['num_sentences', 'num_words','num_chars']].describe()

       num_sentences    num_words    num_chars
count    5169.000000  5169.000000  5169.000000
mean        1.965564    18.455794    78.977945
std         1.448541    13.324758    58.236293
min         1.000000     1.000000     2.000000
25%         1.000000     9.000000    36.000000
50%         1.000000    15.000000    60.000000
75%         2.000000    26.000000   117.000000
max        38.000000   220.000000   910.000000

In [31]:
import seaborn as sns

In [32]:
sns.histplot(df[df['target'] == 0]['num_words'])
sns.histplot(df[df['target'] == 1]['num_words'], color='red')

In [33]:
sns.histplot(df[df['target'] == 0]['num_chars'])
sns.histplot(df[df['target'] == 1]['num_chars'], color='red')

In [34]:
sns.histplot(df[df['target'] == 0]['num_sentences'])
sns.histplot(df[df['target'] == 1]['num_sentences'], color='red')

In [35]:
sns.pairplot(df, hue='target')

In [36]:
df.drop(columns=['text']).corr()

                 target  num_chars  num_words  num_sentences
target         1.000000   0.384717   0.262912       0.263939
num_chars      0.384717   1.000000   0.965760       0.624139
num_words      0.262912   0.965760   1.000000       0.679971
num_sentences  0.263939   0.624139   0.679971       1.000000

In [37]:
sns.heatmap(df.drop(columns=['text']).corr(), annot=True)

### Text Preprocessing
### 1. Lower case
### 2. Tokenisation
### 3. Removing special characters
### 4. Removing stop words and punctuation
### 5. Stemming

In [38]:
import string
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [39]:
ps = PorterStemmer()

In [40]:
def transform_text(text):
    text = text.lower()
    text = nltk.word_tokenize(text)
    
    y = []
    for i in text:
        if i.isalnum():
            y.append(i)
    
    text = y[:]
    y.clear()

    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)
    
    text = y[:]
    y.clear()

    for i in text:
        y.append(ps.stem(i))
    
    return " ".join(y)

In [41]:
transform_text("Did you like the Machine Learning course on Youtube? I liked a lot!")

'like machin learn cours youtub like lot'

In [42]:
df['text'].apply(transform_text)

0       go jurong point crazi avail bugi n great world...
1                                   ok lar joke wif u oni
2       free entri 2 wkli comp win fa cup final tkt 21...
3                     u dun say earli hor u c alreadi say
4                    nah think goe usf live around though
                              ...
5567    2nd time tri 2 contact u pound prize 2 claim e...
5568                                b go esplanad fr home
5569                                    piti mood suggest
5570    guy bitch act like interest buy someth els nex...
5571                                       rofl true name
Name: text, Length: 5169, dtype: object

In [43]:
df['transformed_text'] = df['text'].apply(transform_text)

C:\Users\Corei5_8GBRAM_512SSD\AppData\Local\Temp\ipykernel_12996\283536690.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['transformed_text'] = df['text'].apply(transform_text)

In [44]:
df.head()

,target,text,num_chars,num_words,num_sentences,transformed_text
0,0,"Go until jurong point, crazy.. Available only ...",111,24,2,go jurong point crazi avail bugi n great world...
1,0,Ok lar... Joking wif u oni...,29,8,2,ok lar joke wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155,37,2,free entri 2 wkli comp win fa cup final tkt 21...
3,0,U dun say so early hor... U c already then say...,49,13,1,u dun say earli hor u c alreadi say
4,0,"Nah I don't think he goes to usf, he lives aro...",61,15,1,nah think goe usf live around though

In [45]:
from wordcloud import WordCloud
wc = WordCloud(width=800, height=800, min_font_size=10, background_color='white')

In [46]:
spam_wordcloud = wc.generate(df[df['target']== 1]['transformed_text'].str.cat(sep=" "))
ham_wordcloud = wc.generate(df[df['target']== 0]['transformed_text'].str.cat(sep=" "))

In [47]:
plt.figure(figsize=(6,6))
plt.imshow(spam_wordcloud)

In [48]:
plt.figure(figsize=(6,6))
plt.imshow(ham_wordcloud)

In [49]:
spam_corpus = []
for msg in df[df['target'] == 1]['transformed_text'].to_list():
    for word in msg.split():
        spam_corpus.append(word)

len(spam_corpus)

9939

In [50]:
from collections import Counter
pd.DataFrame(Counter(spam_corpus).most_common(30))

          0    1
0      call  320
1      free  191
2         2  155
3       txt  141
4      text  122
5         u  119
6        ur  119
7     mobil  114
8      stop  104
9     repli  103
10    claim   98
11        4   97
12    prize   82
13      get   74
14      new   64
15   servic   64
16     tone   63
17     send   60
18   urgent   57
19    nokia   57
20  contact   56
21    award   55
22    phone   52
23     cash   51
24    pleas   51
25     week   49
26      win   48
27        c   45
28  collect   45
29      min   45

In [51]:
spam_df = pd.DataFrame(Counter(spam_corpus).most_common(30))

In [52]:
sns.barplot(spam_df, x=0, y=1)
plt.xticks(rotation='vertical')
plt.show()

C:\Users\Corei5_8GBRAM_512SSD\AppData\Local\Temp\ipykernel_12996\4042395929.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [53]:
ham_corpus = []
for msg in df[df['target'] == 0]['transformed_text'].to_list():
    for word in msg.split():
        ham_corpus.append(word)

len(ham_corpus)

35404

In [54]:
ham_df = pd.DataFrame(Counter(ham_corpus).most_common(30))

In [55]:
sns.barplot(ham_df, x=0, y=1)
plt.xticks(rotation='vertical')
plt.show()

C:\Users\Corei5_8GBRAM_512SSD\AppData\Local\Temp\ipykernel_12996\4000171350.py:3: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Model Building

In [56]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score

In [57]:
cv = CountVectorizer()
tfidf = TfidfVectorizer()

### CountVectorizer

In [58]:
X = cv.fit_transform(df['transformed_text']).toarray()

In [59]:
X.shape

(5169, 6708)

In [60]:
from sklearn.model_selection import train_test_split
y = df['target'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [61]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [62]:
gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

In [63]:
gnb.fit(X_train, y_train)
y_pred1 = gnb.predict(X_test)
print(accuracy_score(y_test, y_pred1))
print(confusion_matrix(y_test, y_pred1))
print(precision_score(y_test, y_pred1))

0.8800773694390716
[[792 104]
 [ 20 118]]
0.5315315315315315

In [64]:
mnb.fit(X_train, y_train)
y_pred2 = mnb.predict(X_test)
print(accuracy_score(y_test, y_pred2))
print(confusion_matrix(y_test, y_pred2))
print(precision_score(y_test, y_pred2))

0.9642166344294004
[[871  25]
 [ 12 126]]
0.8344370860927153

In [65]:
bnb.fit(X_train, y_train)
y_pred3 = bnb.predict(X_test)
print(accuracy_score(y_test, y_pred3))
print(confusion_matrix(y_test, y_pred3))
print(precision_score(y_test, y_pred3))

0.9700193423597679
[[893   3]
 [ 28 110]]
0.9734513274336283

### TfidfVectoriser

In [66]:
X = tfidf.fit_transform(df['transformed_text']).toarray()
X.shape
y = df['target'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)
gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

In [67]:
gnb.fit(X_train, y_train)
y_pred1 = gnb.predict(X_test)
print(accuracy_score(y_test, y_pred1))
print(confusion_matrix(y_test, y_pred1))
print(precision_score(y_test, y_pred1))
print("*"*20)
mnb.fit(X_train, y_train)
y_pred2 = mnb.predict(X_test)
print(accuracy_score(y_test, y_pred2))
print(confusion_matrix(y_test, y_pred2))
print(precision_score(y_test, y_pred2))
print("*"*20)
bnb.fit(X_train, y_train)
y_pred3 = bnb.predict(X_test)
print(accuracy_score(y_test, y_pred3))
print(confusion_matrix(y_test, y_pred3))
print(precision_score(y_test, y_pred3))

0.8762088974854932
[[793 103]
 [ 25 113]]
0.5231481481481481
********************
0.9593810444874274
[[896   0]
 [ 42  96]]
1.0
********************
0.9700193423597679
[[893   3]
 [ 28 110]]
0.9734513274336283

### Tfidf - based

In [68]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [69]:
svc = SVC(kernel='sigmoid', gamma=1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression(solver='liblinear', penalty='l1')
rfc = RandomForestClassifier(n_estimators=50, random_state=2)
abc = AdaBoostClassifier(n_estimators=50, random_state=2)
bc = BaggingClassifier(n_estimators=50, random_state=2)
etc = ExtraTreesClassifier(n_estimators=50, random_state=2)
gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)
xgb = XGBClassifier(n_estimators=50,random_state=2)

In [70]:
clfs = {
    'SVC':svc,
    'KNC':knc,
    'MNB':mnb,
    'DTC':dtc,
    'LRC':lrc,
    'RFC':rfc,
    'ABC':abc,
    'BC':bc,
    'ETC':etc,
    'GBDT':gbdt,
    'XGB':xgb
}

In [71]:
def train_n_predict(clf, X_train, y_train, X_test, y_test):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    return accuracy, precision

In [ ]:
# accuracy_scores = []
# precision_scores = []

# for name, clf in clfs.items():
#     curr_acc, curr_pre = train_n_predict(clf, X_train, y_train, X_test, y_test)
#     accuracy_scores.append(curr_acc)
#     precision_scores.append(curr_pre)
#     print("For ", name)
#     print("Accuracy Score: ", curr_acc)
#     print("Precision Score: ", curr_pre)

In [71]:
performance_df = pd.DataFrame({'Algorithm': clfs.keys(), 'Accuracy': accuracy_scores, 'Precision': precision_scores}).sort_values(by='Precision', ascending=False)

In [72]:
performance_df

   Algorithm  Accuracy  Precision
1        KNC  0.900387   1.000000
2        MNB  0.959381   1.000000
5        RFC  0.971954   1.000000
8        ETC  0.972921   0.982456
0        SVC  0.972921   0.974138
10       XGB  0.974855   0.951613
4        LRC  0.951644   0.940000
9       GBDT  0.952611   0.923810
7         BC  0.958414   0.862595
6        ABC  0.924565   0.840909
3        DTC  0.935203   0.838095

In [73]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer(max_features=3000)                           ## Max features = 3000 gives better prediction accuracy on some classifiers
X = tfidf.fit_transform(df['transformed_text']).toarray()
y = df['target'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [75]:
knc = KNeighborsClassifier()
mnb = MultinomialNB()
rfc = RandomForestClassifier(n_estimators=50, random_state=2)

In [76]:
clfs = {
    'KNC':knc,
    'MNB':mnb,
    'RFC':rfc
}

In [77]:
accuracy_scores = []
precision_scores = []

for name, clf in clfs.items():
    curr_acc, curr_pre = train_n_predict(clf, X_train, y_train, X_test, y_test)
    accuracy_scores.append(curr_acc)
    precision_scores.append(curr_pre)
    print("For ", name)
    print("Accuracy Score: ", curr_acc)
    print("Precision Score: ", curr_pre)

For  KNC
Accuracy Score:  0.9052224371373307
Precision Score:  1.0
For  MNB
Accuracy Score:  0.9709864603481625
Precision Score:  1.0
For  RFC
Accuracy Score:  0.9758220502901354
Precision Score:  0.9829059829059829

In [78]:
import pickle

pickle.dump(tfidf, open('vectorizer(max_ft=3000).pkl','wb'))
pickle.dump(rfc, open('model(rfc,max_ft=3000).pkl','wb'))
pickle.dump(mnb, open('model(mnb,max_ft=3000).pkl','wb'))